services:
  mongo:
    image: mongo:4.4.29
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app
    restart: unless-stopped
    environment:
      MONGO_URI: mongodb://mongo:27017
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
